name: Shred History
on: workflow_dispatch
jobs:
  shred:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Shred
        run: |
          git config user.name "shredder"
          git config user.email "shredder@null.com"
          git checkout --orphan temp_branch
          git add -A
          git commit -m "sys_init_01"
          git branch -D main
          git branch -m main
          git push -f origin main
